feat: Support RAW image formats
linuxdeepin/dtkgui pull request #100
Opened 2022-12-30 02:06 UTC by rb-union

1. Dynamically load libraw.so to support RAW image fomats.
2. Improve some implementations, Update unit cases and docs.
3. Update linglong.yaml.

Log: Support RAW image formats.
Influence: Add build dependency libraw-dev.

2022-12-30 02:18 UTC, rb-union commented
/review @kegechen @Groveer @toberyan @xzl01 @dandan-y @uniontechzhangsong

2022-12-30 02:49 UTC, uniontechzhangsong reviewed
+1

2022-12-30 09:37 UTC, kegechen commented on examples/imagehandler-example/main.cpp
>      QCoreApplication app(argc, argv);
QPlatformPixmap: QGuiApplication required

2022-12-30 10:08 UTC, rb-union commented on examples/imagehandler-example/main.cpp
>      QCoreApplication app(argc, argv);
已修改此问题。

2022-12-31 13:50 UTC, xzl01 approved these changes
建议将example在文档中也放一份 并且配合一定说明 方便文档阅读者理解，格式就正常用markdown就行

2023-01-06 08:33 UTC, xzl01 commented on docs/src/dimagehandler.zh_CN.dox
> +@param intensity[in] 滤镜处理强度，取值范围 -255 ~ 255 ，默认30
感觉这样写应该不太对  应该是 @param[in] intensity .....

2023-01-06 08:35 UTC, xzl01 requested changes
文档问题需要修改下

2023-01-10 02:34 UTC, zccrs requested changes

2023-01-10 02:34 UTC, zccrs commented on CMakeLists.txt
> +pkg_check_modules(libraw REQUIRED IMPORTED_TARGET libraw)
要做成可选的，不强制依赖 libraw，允许在编译时禁用 libraw 的相关功能。而且可以默认就禁用，在 debian/rules 中开启，这样其它发行版默认就不会需要增加依赖。

2023-01-28 05:08 UTC, xzl01 submitted a review, later dismissed
+1

2023-01-30 03:21 UTC, rb-union commented on docs/src/dimagehandler.zh_CN.dox
> +@param intensity[in] 滤镜处理强度，取值范围 -255 ~ 255 ，默认30
已修改并在文档中添加示例的描述

2023-01-30 03:27 UTC, rb-union commented on CMakeLists.txt
> +pkg_check_modules(libraw REQUIRED IMPORTED_TARGET libraw)
添加了编译选项 DTK_DISABLE_EX_IMAGE_FORMAT ，同时根据编译环境判断是否允许支持拓展格式，在RPM和Arch构建下默认不编译。
但后续看图等软件会使用相关接口，仍在debian和linglong构建下保留了依赖项。

2023-01-30 05:07 UTC, rb-union commented
/recheck build-deb/check_job/build

2023-01-30 05:18 UTC, rb-union commented
/recheck build-deb/check_job/build

2023-01-30 07:01 UTC, rb-union commented
/recheck /build-deb/check_job/build

2023-01-30 07:02 UTC, rb-union commented
/check

2023-01-30 09:49 UTC, rb-union commented
/check commitlint/check_job/commitlint

2023-01-30 09:50 UTC, rb-union commented
/check

2023-01-31 01:25 UTC, rb-union commented
> 文档问题需要修改下

2023-01-31 01:43 UTC, rb-union commented
/review @zccrs

2023-02-02 02:33 UTC, rb-union commented
/merge

2023-02-02 02:33 UTC, merged