feat: add icon finder for dci-icon-theme
linuxdeepin/dtkgui pull request #117
Opened 2023-02-02 07:54 UTC by kegechen

dci-icon-theme --findIcon deb
"deb" [ "xxx-icon" ]: "/usr/share/dsg/icons/xxx-icon/deb.dci"

Log: none
Change-Id: Ide152e0ba1cba0fb0252ead7304c255a2c0695d4

2023-02-02 08:43 UTC, zccrs requested changes

2023-02-02 08:43 UTC, zccrs commented on tools/dci-icon-theme/main.cpp
> +    QCommandLineOption iconFinder("findIcon", "find dci icon path");
直接叫  "find" 不就好了

2023-02-02 08:43 UTC, zccrs commented on tools/dci-icon-theme/main.cpp
> +        if (auto cached = DIconTheme::cached()) {
对于find工具而言可以忽略cache，这个工具运行一次就退出了，也不会有cache

2023-02-02 08:45 UTC, zccrs requested changes

2023-02-02 08:45 UTC, zccrs commented on tools/dci-icon-theme/main.cpp
> +    QCommandLineOption iconFinder("findIcon", "find dci icon path");
"find dci icon path" "find" 首字母要大写。
建议改成 "Find dci icon file path"

2023-02-03 03:06 UTC, zccrs requested changes

2023-02-03 03:06 UTC, zccrs commented on tools/dci-icon-theme/main.cpp
> +        qWarning() << "Not give a" << (isIconFinder ? "iconName." : "source directory.");
应该是 "Not give a icon name"而不是 "Not give a iconName"

2023-02-03 09:14 UTC, asterwyx submitted a review, later dismissed

2023-02-03 10:00 UTC, zccrs requested changes

2023-02-03 10:00 UTC, zccrs commented on tools/dci-icon-theme/main.cpp
> +        QString iconThemeName = DGuiApplicationHelper::instance()->applicationTheme()->iconThemeName();
建议也支持下指定 theme name，未指定时使用默认的。

2023-02-06 02:15 UTC, zccrs approved these changes

2023-02-06 02:25 UTC, zccrs requested changes
需要改下 copyright 的年份

2023-02-06 05:12 UTC, zccrs requested changes

2023-02-06 05:12 UTC, zccrs commented on tools/dci-icon-theme/main.cpp
> +// SPDX-FileCopyrightText: 2023 UnionTech Software Technology Co., Ltd.
应该是 2022-2023

2023-02-06 05:32 UTC, zccrs approved these changes

2023-02-06 05:33 UTC, merged