fix: dci icon image scale calculation error
linuxdeepin/dtkgui pull request #134
Opened 2023-03-09 02:45 UTC by kegechen

qreal pixmapScale = 48 / 256; // 0
qreal pixmapScale = qreal(48) / 256; // 0.1875

Log: dci image size calculation error

2023-03-09 02:51 UTC, kegechen commented
请求一个小的图标，计算错误的问题。现象是dock中图标都是花的。
dci图标中是256. 请求一个48大小的图标会是一个 imageSize 为 0 的图。。

2023-03-09 03:26 UTC, zccrs requested changes
加个单元测试，测一下目标大小与原图大小不一样的情况

2023-03-09 03:46 UTC, kegechen commented
> 加个单元测试，测一下目标大小与原图大小不一样的情况

dciicon 没有单元测试，我补一下

2023-03-10 01:32 UTC, 18202781743 commented on tests/src/ut_ddciicon.cpp
> +        : icon(QStringLiteral(":/images/dci_heart.dci")) {}
dci_heart 这个文件存在么，

2023-03-10 01:33 UTC, kegechen commented on tests/src/ut_ddciicon.cpp
> +        : icon(QStringLiteral(":/images/dci_heart.dci")) {}
这是另外一个ut, 动画的ut引入的一个资源文件。存在

2023-03-10 01:35 UTC, zccrs approved these changes

2023-03-10 01:35 UTC, 18202781743 approved these changes

2023-03-10 06:41 UTC, merged