chore: option to use KIconThemes instead of Qt5XdgIconLoader
linuxdeepin/dtkgui pull request #135
Opened 2023-03-13 03:04 UTC by BLumia

提供选项，使用 KIconThemes 替代 Qt5XdgIconLoader。

目前加了一些 ifdef 去判断用哪个，但我们还有必要保留使用 Qt5XdgIconLoader 的实现吗？

2023-03-13 03:15 UTC, asterwyx requested changes

2023-03-13 03:15 UTC, asterwyx commented on CMakeLists.txt
> +feature_summary(WHAT ALL INCLUDE_QUIET_PACKAGES FATAL_ON_MISSING_REQUIRED_PACKAGES)
结尾空行。

2023-03-13 03:15 UTC, asterwyx commented on src/CMakeLists.txt
> +        target_link_libraries(${LIB_NAME} PRIVATE KF5::IconThemes)
依赖KF会不会导致DTK在V23上引入一堆kde相关的依赖。

2023-03-13 03:15 UTC, asterwyx commented on CMakeLists.txt
>  option(DTK_DISABLE_LIBRSVG "Disable librsvg" OFF)
这两个可以改成依赖DTK_DISABLE_ICON_ENGINE_PROXY的条件选项。

2023-03-13 03:15 UTC, asterwyx commented on src/util/util.cmake
> +  add_definitions(-DDTK_DISABLE_LIBXDG)
这里逻辑是不是反了。

2023-03-13 03:18 UTC, BLumia commented on src/CMakeLists.txt
> +        target_link_libraries(${LIB_NAME} PRIVATE KF5::IconThemes)
KIconThemes 应该还好。如果只是从依赖的角度看的话，KIconThemes 依赖 KArchive，而这个依赖本身也不算重。其它没有牵连到较多 KF 相关的依赖。

2023-03-13 03:28 UTC, BLumia commented on CMakeLists.txt
>  option(DTK_DISABLE_LIBRSVG "Disable librsvg" OFF)
指的是 `cmake_dependent_option` 吗？

2023-03-13 03:33 UTC, BLumia commented on CMakeLists.txt
>  option(DTK_DISABLE_LIBRSVG "Disable librsvg" OFF)
以按照 `cmake_dependent_option` 更新代码

2023-03-13 05:10 UTC, zccrs requested changes

2023-03-13 05:10 UTC, zccrs commented on src/util/dicontheme.cpp
>  static inline QIconEngine *createXdgProxyIconEngine(const QString &iconName)
函数名改改

2023-03-13 05:10 UTC, zccrs commented on CMakeLists.txt
> +option(DTK_DISABLE_ICON_ENGINE_PROXY "Disable icon engine, use QIcon::fromTheme() as possible fallback" OFF)
同步更新一下readme？

2024-01-12 06:39 UTC, BLumia commented
目前没空处理这个了，暂时关闭，回头可能要单独重搞下这个或者 fork 一份 KIconTheme 改改用

2024-01-12 06:39 UTC, closed without merging