feat: add DIconTheme::createIconEngine
linuxdeepin/dtkgui pull request #136
Opened 2023-03-13 09:44 UTC by kegechen

DIconTheme::createIconEngine for qt5integration
1. try createBuiltinIconEngine first
2. try createXdgProxyIconEngine or fallback to fromTheme 
Warning : do not call from qplatformTheme createIconEngine without DontFallbackToQIconFromTheme flag

Log: add createIconEngine

2023-03-14 08:50 UTC, zccrs requested changes

2023-03-14 08:50 UTC, zccrs commented on src/util/dicontheme.cpp
> +        return nullptr;
不用返回空，可以返回 new QIconLoaderEngine(name)

2023-03-15 03:41 UTC, kegechen commented on src/util/dicontheme.cpp
> +        return nullptr;
undefined reference to `QIconLoaderEngine::QIconLoaderEngine(QString const&)'
这个 `QIconLoaderEngine` 只导出了一个符号  `Q_GUI_EXPORT static QIconLoaderEngineEntry *entryForSize`

2023-03-15 03:58 UTC, kegechen commented on src/util/dicontheme.cpp
> +    return QIcon::fromTheme(iconName).data_ptr()->engine;
同上。失败只能返回空了。

2023-03-15 05:03 UTC, zccrs commented on src/util/dicontheme.cpp
> +    bool hasUserTheme = QIconLoader::instance()->hasUserTheme();
我们这里有必要判断这个吗

2023-03-15 09:22 UTC, zccrs requested changes

2023-03-15 09:22 UTC, zccrs commented on src/util/dicontheme.cpp
> +QIconEngine *DIconTheme::createIconEngine(const QString &iconName, Options options)
差点漏掉了文档这个事情，其他接口可以先不管，这个新增加的 public 接口要加下文档。

2023-03-21 05:25 UTC, xzl01 submitted a review, later dismissed
+1

2023-03-21 05:49 UTC, zccrs requested changes

2023-03-21 05:49 UTC, zccrs commented on docs/util/dicontheme.zh_CN.dox
> +    |   键   | 值 |
不要用表格，可以直接用 doxygen 的 enum 相关的语法。
可以参考 DDciIconPlayer

2023-03-21 05:49 UTC, zccrs commented on docs/util/dicontheme.zh_CN.dox
> +@details 通过指定图标名 iconName 和主题名 themeName 查找 Dci 图标文件路径的接口，找到时会加入缓存
DCI单独作为名词出现时使用纯大写

2023-03-21 05:49 UTC, zccrs commented on docs/util/dicontheme.zh_CN.dox
> +@details 返回 QIcon 是否为内置图标（图标引擎为 DBuiltinIconEngine）
不需要在文档里体现 DBuiltinIconEngine这类私有内容，这样反而会让阅读者对DBuiltinIconEngine是什么产生疑问，而且在文档里又不可能对它答疑。这里可以这样说：

`返回 QIcon 是否为内置图标，“内置图标”是DTK中规定的一类集成在二进制内部的图标资源，其一般放置于 qrc://.......，在使用 findQIcon 或 createIconEngine 时，如找到此目录下对应的图标文件，则会为其使用一个自定义的 QIconEngine 进行渲染。此方法即通过判断 icon 所使用的 QIconEngine 确认其是否为内置图标。`

另外应该在 findQIcon 和 createIconEngine 的文档中说清楚图标查找目录的优先级。如果findQIcon的实现主要依赖于 createIconEngine ，那在文档里不用重复描述两遍，直接说findQIcon的QIcon是使用createIconEngine创建的engine构造的就行了。

2023-03-21 05:49 UTC, zccrs commented on docs/util/dicontheme.zh_CN.dox
> +@details 返回 QIcon 是否为 Xdg 图标（图标引擎为 XdgIconProxyEngine）
同上

2023-03-21 08:23 UTC, zccrs approved these changes

2023-03-22 09:33 UTC, merged