feat: add config file
linuxdeepin/dtkgui pull request #139
Opened 2023-03-22 07:19 UTC by chenchongbiao

添加自定义UI的配置文件

log:

2023-03-22 07:20 UTC, chenchongbiao commented
/review @zccrs

2023-03-22 07:54 UTC, zccrs requested changes

2023-03-22 07:54 UTC, zccrs commented on configs/org.deepin.dtk.ui.preference.json
> +            "flags": ["nooverride"],
为什么要加 nooverride flag？

2023-03-22 07:54 UTC, zccrs commented on configs/org.deepin.dtk.ui.preference.json
> +            "description": "Configure the height of the DTitleBar",
desciption 也可以加一个 description[zh_CN]

2023-03-22 07:54 UTC, zccrs commented on configs/org.deepin.dtk.ui.preference.json
> +}
文件以一个空行结尾

2023-03-22 07:59 UTC, zccrs requested changes
另外修改下commit信息，可以不用写一个空的“log:”

2023-03-22 08:07 UTC, zccrs commented on configs/org.deepin.dtk.ui.preference.json
> +            "flags": ["nooverride"],
nooverride是表明不允许被 override 机制覆盖它，绝大多数配置项都不需要添加它，如果你不确定要不要加它，那选择不加它是对的。

2023-03-22 08:09 UTC, chenchongbiao commented on configs/org.deepin.dtk.ui.preference.json
> +            "flags": ["nooverride"],
好的

2023-03-22 11:38 UTC, chenchongbiao commented
这个打包服务器不识别dconfig_meta_files指令

2023-03-23 01:18 UTC, zccrs commented
> 这个打包服务器不识别dconfig_meta_files指令

应该需要在调用前 include 一些什么，参考dtkwidget 看看

2023-03-23 03:07 UTC, chenchongbiao commented
> > 这个打包服务器不识别dconfig_meta_files指令
> 
> 应该需要在调用前 include 一些什么，参考dtkwidget 看看

行

2023-03-23 05:57 UTC, kegechen commented on configs/org.deepin.dtk.ui.preference.json
json 文件可以放到 misc 中

2023-03-23 08:37 UTC, zccrs submitted a review, later dismissed

2023-03-23 11:17 UTC, chenchongbiao commented
/merge

2023-03-27 01:03 UTC, kegechen requested changes

2023-03-27 01:03 UTC, kegechen commented on CMakeLists.txt
> +find_package(Dtk REQUIRED COMPONENTS Core)
@asterwyx @wineee  这个改动不是去掉了 dtkcore 版本依赖了？

2023-03-27 01:35 UTC, wineee commented on CMakeLists.txt
> +find_package(Dtk REQUIRED COMPONENTS Core)
可以试试 `find_package(Dtk 5.6 REQUIRED COMPONENTS Core)`

2023-03-27 03:48 UTC, chenchongbiao commented on CMakeLists.txt
> +find_package(Dtk REQUIRED COMPONENTS Core)
> find_package(Dtk 5.6 REQUIRED COMPONENTS Core)

好的 原本这样打包服务器过不了 找不到dconfig_meta_files指令，这指令原本在DtkCommon那里的

2023-03-27 03:51 UTC, wineee commented on CMakeLists.txt
> +find_package(Dtk REQUIRED COMPONENTS Core)
这个可以在使用 dconfig_meta_files 的项目里加上 `find_package(Dtk)` 试试

2023-03-27 04:20 UTC, chenchongbiao commented on CMakeLists.txt
> +find_package(Dtk REQUIRED COMPONENTS Core)
还是过不了那句find_package(Dtk 5.6 REQUIRED COMPONENTS Core)

CMake Error at CMakeLists.txt:115 (find_package):
Could not find a configuration file for package "Dtk" that is compatible
 with requested version "5.6".

2023-03-27 04:29 UTC, chenchongbiao commented on CMakeLists.txt
> +find_package(Dtk REQUIRED COMPONENTS Core)
我看dtkwidget也用了dconfig_meta_files，不过没限制DtkCore的版本

2023-03-27 05:03 UTC, wineee commented on CMakeLists.txt
> +find_package(Dtk REQUIRED COMPONENTS Core)
DtkCMakeConfig.cmake 没有提供版本信息，那就不能在这里检查版本了

2023-03-27 05:20 UTC, wineee commented on CMakeLists.txt
> +find_package(Dtk REQUIRED COMPONENTS Core)
也许可以手动判断下
```
find_package(Dtk REQUIRED COMPONENTS Core)
if (NOT DtkCore_VERSION VERSION_EQUAL CMAKE_PROJECT_VERSION)
        message(WARNING, "build dtkgui ${CMAKE_PROJECT_VERSION}, but find dtkcore ${DtkCore_VERSION}")
endif()
```

2023-03-27 05:29 UTC, Decodetalkers commented on CMakeLists.txt
> +find_package(Dtk REQUIRED COMPONENTS Core)
DtkDConfig 可以单独find的啊

2023-03-28 02:13 UTC, asterwyx commented on CMakeLists.txt
> +find_package(Dtk REQUIRED COMPONENTS Core)
> 这个可以在使用 dconfig_meta_files 的项目里加上 `find_package(Dtk)` 试试

这个是万万不能的，不推荐使用find_package(Dtk)

2023-03-28 02:15 UTC, asterwyx commented on CMakeLists.txt
> +find_package(Dtk REQUIRED COMPONENTS Core)
> @asterwyx @wineee 这个改动不是去掉了 dtkcore 版本依赖了？

这里要指定版本是要干什么呢，我们应该只有一个版本的Dtk可以安装在系统里吧，如果是因为DConfig，使用find_package(Dtk COMPONENTS REQUIRED Core)的方式没有问题。

2023-03-29 01:47 UTC, zccrs commented on CMakeLists.txt
> +find_package(Dtk REQUIRED COMPONENTS Core)
DTK后边要统一版本号，这里的版本指定可以去掉，今后应当是只保障DTK各版本在相同版本号之下的编译，混用版本为未定义行为。

2023-03-29 02:06 UTC, kegechen approved these changes

2023-03-29 02:22 UTC, chenchongbiao commented
/merge

2023-03-29 02:22 UTC, merged