chore: fix compile warning
linuxdeepin/dtkgui pull request #151
Opened 2023-04-26 10:02 UTC by Decodetalkers

Log: fix compile warning

2023-04-27 05:43 UTC, zccrs requested changes

2023-04-27 05:43 UTC, zccrs commented on src/kernel/dguiapplicationhelper.cpp
> +        const QStringList parseLocalNameList = locale.name().split("_", Qt::SkipEmptyParts);
要考虑Qt5.11

2023-04-27 05:43 UTC, zccrs commented on src/kernel/dnativesettings.cpp
> +        debug << key << settings.getSetting(key) << Qt::endl;
同上

2023-04-27 05:57 UTC, zccrs requested changes

2023-04-27 05:57 UTC, zccrs commented on src/kernel/dguiapplicationhelper.cpp
> +#if QT_VERSION > QT_VERSION_CHECK(5, 14, 0)
应该是 >= ，另外检查其他地方要不要加类似的判断，我没有逐个看。

2023-04-27 06:23 UTC, zccrs requested changes

2023-04-27 06:23 UTC, zccrs commented on src/kernel/dguiapplicationhelper.cpp
> +#if QT_VERSION >= QT_VERSION_CHECK(5, 15, 0)
Qt文档里不是说了5.14版本中实现或者修改的这个枚举吗，为什么变成了大于等于 5.15 了？

2023-05-05 03:08 UTC, kegechen commented
提交有点杂， 又是resuse的修改，又是 warning 的修改， 还有代码风格的修改（而且单行的 `if` 可以不带大括号也不是风格问题）。
分成多个提交吧。

2023-05-06 05:02 UTC, kegechen commented
+1

2023-05-08 05:15 UTC, kegechen commented
error or warning ？

2023-05-08 05:19 UTC, Decodetalkers commented
> error or warning ？

warning.. 搞错了

2023-06-08 03:19 UTC, kegechen commented
#158 一起改了

2023-06-08 03:23 UTC, Decodetalkers commented
> #158 一起改了

那我关了吧

2023-10-09 01:01 UTC, closed without merging