feat: DIconTheme::findQIcon add fallback icon
linuxdeepin/dtkgui pull request #155
Opened 2023-05-08 05:14 UTC by kegechen

support fallback icon

替换 QIcon：：FromTheme 时很有用

2023-05-15 03:18 UTC, zccrs requested changes

2023-05-15 03:18 UTC, zccrs commented on src/util/dicontheme.cpp
> +QIcon DIconTheme::findQIcon(const QString &iconName, const QIcon &fallback, Options options)
加上文档

2023-05-15 03:19 UTC, 18202781743 submitted a review, later dismissed

2023-07-17 07:52 UTC, zccrs approved these changes

2023-07-18 03:00 UTC, merged