fix: 修复异常退出时再次启动失败的问题
linuxdeepin/dtkgui pull request #18
Opened 2022-03-29 09:39 UTC by kegechen

reverts commit 88e0b51da793d3d8b9d48c8515ddf1bf71814860
去掉原来通过共享内存记录pid的方式来避免快速启动应用导致单进程失败的实现
改成启动时通过QLockFile来确保是 server 还是 client。保证只有一个 server ，其他
都是 client （旧逻辑：启动先通过localsocket连接 localserver，连接失败再启动
server，正常启动时没有问题， 当脚本快速多次启动(detached)单进程应用时，都在
等待连接，超时之后就启动了多个应用）

Bug: https://pms.uniontech.com/bug-view-111699.html
Influence: single-instance
Change-Id: I9b38e039abbbd70de969a1abf2f4f37fe07e1315

2022-03-29 09:47 UTC, zccrs requested changes
试一下进程异常推出后再启动有没有问题

2022-03-29 09:47 UTC, zccrs commented on src/kernel/dguiapplicationhelper.cpp
> +        qWarning() << _d_singleServer->errorString();
在输出_d_singleServer->errorString()之前加一些解释性的内容

2022-03-29 09:47 UTC, zccrs commented on src/kernel/dguiapplicationhelper.cpp
> -#ifdef QT_DEBUG
这个可以保留着用

2022-03-29 09:47 UTC, zccrs commented on src/kernel/dguiapplicationhelper.cpp
> +            qInfo() << "Process is started: pid=" << pid << "arguments=" << arguments;
用qCInfo

2022-03-29 09:47 UTC, zccrs commented on src/kernel/dguiapplicationhelper.cpp
> +        qWarning() << _d_singleServer->errorString();
另外改用qCWarning

2022-03-29 10:08 UTC, kegechen commented on src/kernel/dguiapplicationhelper.cpp
> +        qWarning() << _d_singleServer->errorString();
done

2022-03-29 10:09 UTC, kegechen commented on src/kernel/dguiapplicationhelper.cpp
> +            qInfo() << "Process is started: pid=" << pid << "arguments=" << arguments;
done

2022-03-31 01:43 UTC, kegechen commented
> 

异常退出为发现问题，kill -9 下次依然可以启动

2022-04-01 03:10 UTC, zccrs approved these changes

2022-04-02 06:16 UTC, merged