chore: Adaptation for Qt5.11
linuxdeepin/dtkgui pull request #186
Opened 2023-08-01 06:06 UTC by starhcq

Adaptation for Qt5.11

Log: Adaptation for Qt5.11

2023-08-01 06:25 UTC, kegechen commented on src/kernel/dguiapplicationhelper.cpp
> +        return de.toLower().contains("deepin") || de != "DDE";
逻辑写反了，这里是 包含deepin 或者是 DDE （v23）

2023-08-01 07:07 UTC, kegechen requested changes

2023-08-01 07:07 UTC, kegechen commented on cmake/libraw.cmake
这个查找的方式有点不太友好。。去掉cmake.之保留cpp的修改吧

2023-08-01 10:34 UTC, kegechen commented on include/kernel/dguiapplicationhelper.h
> +    QStringList getEnvsourcePath();
不暴露出来， 放到cpp的static方法吧

2023-08-01 10:37 UTC, kegechen commented on include/kernel/dguiapplicationhelper.h
> +    bool hasUserManual(const QString appName = "");
```cpp
bool hasUserManual(const QString appName)const;
```
二义性

2023-08-01 10:41 UTC, kegechen commented on dtkgui.cmake
> +add_definitions(-DDMAN_MANUAL_DIR="${CMAKE_INSTALL_PREFIX}/share/deepin-manual/manual-assets")
target_compile_definitions 减小范围

2023-08-01 10:43 UTC, kegechen commented on src/kernel/dguiapplicationhelper.cpp
> +            qDebug() << " all MD source path : " << sourcePath.last();
去掉debug调试

2023-08-02 02:27 UTC, 18202781743 commented on src/kernel/dguiapplicationhelper.cpp
> +    QString tempAppName = appName;
既然指定了appName,这里可以不用fallback,直接让外部传递

2023-08-02 02:27 UTC, 18202781743 commented on src/kernel/dguiapplicationhelper.cpp
> +            if (systemType.contains(type)) {
既然只在这里使用了，可以将定义移到这里，并且加上static,
如果只是旧的兼容， 处理逻辑是一样的，可以放到一起，只是优先级较低而已，

2023-08-02 02:27 UTC, 18202781743 commented on src/kernel/dguiapplicationhelper.cpp
> +
返回manualDirs的查找列表，可以合并成一个函数，只是优先级不同而已，

2023-08-02 02:27 UTC, 18202781743 commented on src/kernel/dguiapplicationhelper.cpp
> +#ifdef LINGLONG_BUILD
玲珑应用需要单独处理么？非玲珑应用应该也可以用这个环境变量的路径吧，
目前DConfig兼容玲珑应用的做法是，先查找环境变量，再fallback到一些默认路径，

2023-08-02 02:37 UTC, 18202781743 commented on dtkgui.cmake
> +add_definitions(-DDMAN_MANUAL_DIR="${CMAKE_INSTALL_PREFIX}/share/deepin-manual/manual-assets")
这个宏是不是可以不用要，QStandardPaths::GenericDataLocation 已经包含了/usr/share目录，我们可以对这里的目录做个拼接，
接上/deepin-manual/manual-assets这部分作为目录，这样的话就不用定义这个宏了，

逻辑是，我们准备一系列的manual存放列表，他们直接有优先级，然后去那里挨个匹配，

2023-08-02 05:39 UTC, kegechen commented on src/kernel/dguiapplicationhelper.cpp
> +    QString xdgDataDirs = qgetenv("XDG_DATA_DIRS");
GenericDataLocation 已经包含了  XDG_DATA_DIRS 路径

2023-08-02 05:50 UTC, 18202781743 commented on src/kernel/dguiapplicationhelper.cpp
> +            if (type == "system" || type == "application"
直接放到那个systemType的list就行了，

2023-08-02 05:50 UTC, 18202781743 commented on src/kernel/dguiapplicationhelper.cpp
> +    if (appName.isEmpty())
可以直接assert，

2023-08-02 05:50 UTC, 18202781743 commented on src/kernel/dguiapplicationhelper.cpp
> +        if (pathlist[i].contains("persistent") || pathlist[i].contains("usr/share")) {
直接拼接可以吧，尽量不这样判断路径，
可以加入先拼接形成的路径，再加入GenericDataLocation的路径，

2023-08-02 05:50 UTC, 18202781743 commented on src/kernel/dguiapplicationhelper.cpp
>  #else
不需要linux判断了，另外 直接return hasUserManual(qApp->applicationName());

2023-08-02 05:50 UTC, 18202781743 commented on src/kernel/dguiapplicationhelper.cpp
> +    return moduleList.contains(appName);
应该是判断xxx/appName目录是否存在吧，
另外这里三层for循环，应该可以提前return,

2023-08-02 05:54 UTC, 18202781743 commented on src/kernel/dguiapplicationhelper.cpp
> +QStringList DGuiApplicationHelperPrivate::getMdsourcePath() const
这种跟数据无关的，可以不放到private里，直接写个静态函数就行，

2023-08-02 05:59 UTC, 18202781743 commented on src/kernel/dguiapplicationhelper.cpp
> +    foreach (auto strManualPath, strManualPathList) {
```

for (const auto dir: userMaunalDirs()) {
    for (const auto type: systemTypes) {
         if (QDir(QString("%1/%2/%3").arg(path).arg(type).arg(appName).exist())
               return true;
    }
}
return false;
```

2023-08-02 07:46 UTC, 18202781743 commented on include/kernel/dguiapplicationhelper.h
> +    // 获取md文件路径
这个可以改下，跟下面的hasUserManual对应，
static QStringList userManualDirs();
另外，帮助手册如果需要加载这个文件，是不是只暴露这个目录不够啊，不然还得自己继续往下拼接，
看要不要直接返回查找到的文档目录，

2023-08-02 07:46 UTC, 18202781743 commented on src/kernel/dguiapplicationhelper.cpp
> +                if (modules.contains(appName))
这个用字符串匹配，不太准确吧，可以直接判断目录是否存在，

2023-08-02 08:25 UTC, kegechen commented on tests/src/ut_dfiledrag.cpp
> +#if QT_VERSION >= QT_VERSION_CHECK(5, 15, 0)
如果没有QScopeGuard， 应该在结束的时候delete. 可以换成 QScopePointer 管理

2023-08-02 08:27 UTC, kegechen commented on src/kernel/dguiapplicationhelper.cpp
> +    QStringList moduleList;
cppcheck ： cc

2023-08-02 09:11 UTC, kegechen commented on tests/src/ut_dfiledrag.cpp
> +    drag->setMimeData(m.data());
不应该在这个commit中修改。。。

2023-08-03 00:54 UTC, kegechen submitted a review, later dismissed

2023-08-03 02:01 UTC, starhcq commented
/merge

2023-08-03 02:19 UTC, kegechen commented on include/kernel/dguiapplicationhelper.h
> +    static QStringList userManualDirs();
这个接口需要暴露吗？

2023-08-03 02:21 UTC, kegechen commented on include/kernel/dguiapplicationhelper.h
> +    bool hasUserManual(const QString &appName) const;
```suggestion
    QStringList userManual(const QString &appName) const;  // 直接返回找到的路径
```

2023-08-03 02:23 UTC, kegechen commented on src/kernel/dguiapplicationhelper.cpp
> +        if (pathlist[i].startsWith("/persistent") || pathlist[i].startsWith("/usr/share")) {
不需要判断这么精确，只要在 GenericDataLocation 中找到即可。 这样用户还可以 override
而且 这个 persistent 可能还会改动

2023-08-03 02:27 UTC, kegechen commented on src/kernel/dguiapplicationhelper.cpp
> +            if (systemType.contains(type)) {
```suggestion
{
```

2023-08-03 02:28 UTC, kegechen commented on src/kernel/dguiapplicationhelper.cpp
> +            if (systemType.contains(type)) {
这个判断不需要

2023-08-03 03:19 UTC, kegechen commented on include/kernel/dguiapplicationhelper.h
> +    static QStringList userManual(const QString &appName);
```suggestion
    static QStringList userManualPaths(const QString &appName);
```

2023-08-03 03:42 UTC, kegechen approved these changes

2023-08-03 03:44 UTC, merged