feat: auto load qt translations
linuxdeepin/dtkgui pull request #212
Opened 2023-12-15 06:39 UTC by kegechen

Normally, Qt applications need to explicitly load translations by themselves, including Qt translations. Here we take the initiative to help applications that have loaded dtk (including plugins) load translations.

Issue: https://github.com/linuxdeepin/developer-center/issues/6417

2023-12-15 07:45 UTC, kegechen commented on src/kernel/dguiapplicationhelper.cpp
> +        DGuiApplicationHelper::loadTranslator();
可能会重复加载，应用再加载的话

2023-12-18 01:53 UTC, zccrs requested changes

2023-12-18 01:53 UTC, zccrs commented on src/kernel/dguiapplicationhelper.cpp
> +        DGuiApplicationHelper::loadTranslator();
让应用自己加载不就行了，否则在非DDE、非KDE环境上应用程序怎么办？这本来就是一个没有保障的事情。

2023-12-18 02:44 UTC, kegechen commented on src/kernel/dguiapplicationhelper.cpp
> +        DGuiApplicationHelper::loadTranslator();
那就要到输入法插件改了。

2023-12-18 02:44 UTC, kegechen commented
输入法插件改

2023-12-18 02:44 UTC, closed without merging