chore: dplatformhandle tweak
linuxdeepin/dtkgui pull request #220
Opened 2024-01-22 05:26 UTC by kegechen

1. check systemtheme is valid
2. typo fix. CreatorWindowEventFile==>WindowCreateEvenFilter

2024-01-22 05:29 UTC, kegechen commented on src/kernel/dplatformhandle.cpp
> +        return;
不判断时，如果 `xsettings` 无效（没设置）时就不应该设置默认圆角。
如 `kwin` 如果启动比 `startdde` 早，`xsettings` 获取不到圆角就始终是 `18`

2024-01-22 05:30 UTC, kegechen commented on src/kernel/dplatformhandle.cpp
> -class Q_DECL_HIDDEN CreatorWindowEventFile : public QObject {
Filter ？

2024-01-22 05:40 UTC, kegechen commented
https://github.com/linuxdeepin/developer-center/issues/5743
https://github.com/linuxdeepin/qt5integration/pull/210

2024-01-22 06:13 UTC, 18202781743 commented on src/kernel/dplatformhandle.cpp
> +        return;
后面的连接信号也不做了么？

2024-01-22 06:14 UTC, zccrs requested changes

2024-01-22 06:14 UTC, zccrs commented on src/kernel/dplatformhandle.cpp
> +        return;
应该只在 `!theme->isValid` 时不调用 `setWindowProperty`，不应该跳过后面的 connect 相关的流程

2024-01-23 02:28 UTC, 18202781743 approved these changes

2024-02-29 05:43 UTC, zccrs approved these changes

2024-02-29 05:43 UTC, zccrs requested changes

2024-02-29 05:43 UTC, zccrs commented on src/kernel/dplatformhandle.cpp
> +        setWindowProperty(window, _windowRadius, radius);
theme 无效时是不是应该直接设置为18？

2024-03-22 03:43 UTC, kegechen commented on src/kernel/dplatformhandle.cpp
> +        setWindowProperty(window, _windowRadius, radius);
那就没有必要检查valid了。

2024-03-22 03:43 UTC, kegechen commented
abandon

2024-03-22 03:43 UTC, closed without merging