fix: icon doesn't update when iconTheme changed
linuxdeepin/dtkgui pull request #221
Opened 2024-01-22 09:02 UTC by 18202781743

Adding icon's themeName as a part of the cache key.

2024-01-23 08:01 UTC, FeiWang1119 approved these changes

2024-01-23 08:54 UTC, asterwyx requested changes

2024-01-23 08:54 UTC, asterwyx commented on src/util/dicontheme.cpp
> +    const QString cacheKey = themeName + QLatin1Char('/') + iconName + QChar('/') + QString::number(static_cast<int>(options));
统一一下。

2024-01-23 09:53 UTC, BLumia approved these changes

2024-01-23 10:10 UTC, asterwyx approved these changes

2024-01-23 10:10 UTC, merged

2024-02-01 06:15 UTC, 18202781743 commented
https://github.com/linuxdeepin/developer-center/issues/7197