DDciIconImage support static image
linuxdeepin/dtkgui pull request #247
Opened 2024-07-18 06:57 UTC by kegechen

- DDciIconImage support static image
-  animation-dci supports custom icon

2024-07-19 01:21 UTC, zccrs requested changes

2024-07-19 01:21 UTC, zccrs commented on examples/animation-dci/main.cpp
> +#include <qfiledialog.h>
`#include <QFileDialog>`

2024-07-19 01:21 UTC, zccrs commented on examples/animation-dci/main.cpp
> +            player.play(DDciIcon::Normal);
Why?

2024-07-19 01:22 UTC, zccrs requested changes

2024-07-19 01:22 UTC, zccrs commented on src/util/ddciicon.cpp
> +        if (reader->supportsAnimation() || supportNormalImage) {
No

2024-07-19 01:23 UTC, kegechen commented on examples/animation-dci/main.cpp
> +            player.play(DDciIcon::Normal);
setmode会一直播放，play播放一次

2024-07-19 03:32 UTC, kegechen commented on src/util/ddciicon.cpp
> +        if (reader->supportsAnimation() || supportNormalImage) {
ok

2024-07-19 07:49 UTC, zccrs submitted a review, later dismissed

2024-07-23 03:02 UTC, zccrs approved these changes

2024-07-26 05:54 UTC, merged