fix: availableSizes not work on Qt6
linuxdeepin/dtkgui pull request #255
Opened 2024-09-04 09:12 UTC by kegechen

Qt6 QIconEngine::availableSizes will not call
virtual_hook(QIconEngine::AvailableSizesHook

2024-09-06 07:09 UTC, 18202781743 commented on src/util/private/dciiconengine_p.h
> +    QList<QSize> availableSizes(QIcon::Mode mode = QIcon::Normal, QIcon::State state = QIcon::Off);
加上override,

2024-09-10 01:26 UTC, 18202781743 submitted a review, later dismissed

2024-09-10 09:11 UTC, zccrs requested changes

2024-09-10 09:11 UTC, zccrs commented on src/util/private/dbuiltiniconengine.cpp
> +    int N = m_info.entries.size();
const auto N

2024-09-10 09:11 UTC, zccrs commented on src/util/private/dciiconengine.cpp
> +    auto availableSizes = m_dciIcon.availableSizes(dciTheme(), DDciIcon::Normal);
const auto

2024-12-10 01:08 UTC, 18202781743 approved these changes

2024-12-10 02:10 UTC, zccrs approved these changes

2024-12-12 01:57 UTC, merged