chore: add some interfaces about personalization
linuxdeepin/dtkgui pull request #258
Opened 2024-10-10 06:08 UTC by FeiWang1119

add some interfaces about personalization

Log:

2024-10-12 08:57 UTC, kegechen commented on src/CMakeLists.txt
> +if(NOT DTK_DISABLE_TREELAND AND TreeLandProtocols_FOUND)
` set (DTK_DISABLE_TREELAND OFF CACHE BOOL "DISABLE TREELAND！！")`

2024-10-12 09:29 UTC, FeiWang1119 commented on src/CMakeLists.txt
> +if(NOT DTK_DISABLE_TREELAND AND TreeLandProtocols_FOUND)
done

2024-10-14 01:39 UTC, 18202781743 commented on src/CMakeLists.txt
> +    add_compile_definitions(TREELANDPROTOCOLS_FOUND)
加上target, 只需要给指定target添加宏而不是所有的，

2024-10-14 01:39 UTC, 18202781743 commented on src/kernel/dplatformtheme.cpp
> +#if TREELANDPROTOCOLS_FOUND
这些都是从dnativesettings里获取的值，将dplatformtheme的metaobject改掉了，是不是应该将那里的数据源改掉，而不是直接在这一级拦截

2024-10-14 13:11 UTC, zccrs requested changes

2024-10-15 02:12 UTC, FeiWang1119 commented on src/kernel/dplatformhandle.cpp
> +#if TREELANDPROTOCOLS_FOUND
done

2024-10-15 02:12 UTC, FeiWang1119 commented on src/kernel/dguiapplicationhelper.cpp
> +        return qgetenv("DDE_CURRENT_COMPOSITOR") == "TreeLand";
treeland 设置的

2024-10-15 02:13 UTC, FeiWang1119 commented on src/CMakeLists.txt
> +    add_compile_definitions(TREELANDPROTOCOLS_FOUND)
done

2024-10-15 02:13 UTC, FeiWang1119 commented on src/CMakeLists.txt
> +    add_compile_definitions(TREELANDPROTOCOLS_FOUND)
done

2024-10-15 09:22 UTC, FeiWang1119 commented on src/kernel/dplatformhandle.cpp
> +        if (auto *w = qobject_cast<QWindow *>(watched); w && DGuiApplicationHelper::testAttribute(DGuiApplicationHelper::IsTreelandPlatform)) {
不加Treeland的判断,x环境进来移动会崩溃

2024-10-15 12:24 UTC, zccrs requested changes

2024-10-15 12:24 UTC, zccrs commented on include/kernel/dplatforminterface.h
先不要作为public接口，先作为private的，不对外可见

2024-10-15 12:24 UTC, zccrs commented on include/kernel/dplatforminterface.h
> +    virtual int windowRadius() const;
这个应该是针对window的？

2024-10-15 12:24 UTC, zccrs commented on include/kernel/dplatforminterface.h
> +    virtual void setFontName(const QByteArray &fontName);
这种系统全局类的配置的修改不在 dtkgui 里提供，dtkgui里只读，不实现修改的功能。

2024-10-15 12:24 UTC, zccrs commented on include/kernel/dplatforminterface.h
> +    virtual void setFontName(const QByteArray &fontName);
就算要做修改的功能，也应该是在 dtksystemsettings 模块里做。

2024-10-15 12:24 UTC, zccrs commented on include/kernel/dplatforminterface.h
> +    virtual void setWindowRadius(int windowRadius);
如果是针对某个窗口的，那可以留着设置接口

2024-10-15 12:24 UTC, zccrs commented on include/kernel/dxcbplatforminterface.h
作为一个单独的cmake模块放到一个子目录里，目录以 plugins/platform 开头，比如是 plugins/platform/xcb

2024-10-15 12:24 UTC, zccrs commented on include/kernel/dxcbplatforminterface.h
同样的也应该是 private 的，不对外

2024-10-15 12:24 UTC, zccrs commented on src/kernel/dplatformhandle.cpp
> +#ifndef DTK_DISABLE_TREELAND
这部分为什么没有拆到 DPlatformHandle 里去？

2024-10-15 12:24 UTC, zccrs commented on src/kernel/dplatformhandle.cpp
> +    if (DGuiApplicationHelper::testAttribute(DGuiApplicationHelper::IsTreelandPlatform)) {
同上

2024-10-15 12:24 UTC, zccrs commented on src/kernel/dplatforminterface.cpp
> +int DPlatformInterface::windowRadius() const
可以直接是纯虚函数

2024-10-15 12:24 UTC, zccrs commented on src/kernel/dplatformtheme.cpp
> -
为啥删了

2024-10-15 12:24 UTC, zccrs commented on src/wayland/personalizationwaylandclientextension.cpp
> +        QtWaylandClient::QWaylandIntegration *waylandIntegration = static_cast<QtWaylandClient::QWaylandIntegration *>(QGuiApplicationPrivate::platformIntegration());
Qt6版本不是这样使用了吧，它不是有了 QNativeInterface 这种东西

2024-10-15 12:31 UTC, FeiWang1119 commented on include/kernel/dplatforminterface.h
> +    virtual int windowRadius() const;
这个是全局的,控制中心设置系统圆角的

2024-11-28 06:55 UTC, closed without merging