xcb
linuxdeepin/dtkgui pull request #274
Opened 2024-11-20 05:14 UTC by mhduiy

2024-11-21 07:45 UTC, 18202781743 approved these changes

2024-11-21 09:22 UTC, FeiWang1119 approved these changes

2024-11-21 11:25 UTC, zccrs requested changes

2024-11-21 11:25 UTC, zccrs commented on src/plugins/dplatforminterface.h
> +class DPlatformInterface : public QObject, public DCORE_NAMESPACE::DObject
改为私有的，文件加上 _p.h 后缀，这个类不对外。

2024-11-21 11:25 UTC, zccrs commented on src/plugins/dplatforminterface.h
> +    Q_PROPERTY(int cursorBlinkTime READ cursorBlinkTime WRITE setCursorBlinkTime NOTIFY cursorBlinkTimeChanged)
这个interface类里面应该不需要提供属性

2024-11-21 11:25 UTC, zccrs commented on src/kernel/dplatformtheme.cpp
> +    connect(d->platformInterface, &DPlatformInterface::cursorBlinkTimeChanged, this, &DPlatformTheme::cursorBlinkTimeChanged);
这样做太麻烦了， 直接把 DPlatformTheme 对象交给 platformInterface，在interface的实现中直接发送DPlatformTheme的信号。

2024-11-22 10:04 UTC, 18202781743 submitted a review, later dismissed

2024-11-22 10:21 UTC, zccrs requested changes

2024-11-22 10:21 UTC, zccrs commented on src/private/dplatforminterface_p.h
> +class DPlatformInterface
如果要给外面用，需要加上 EXPORT 的宏导出这个类，类似于 LIBDTKCORESHARED_EXPORT

2024-11-22 10:21 UTC, zccrs commented on src/private/dplatformtheme_p.h
> +    DPlatformInterface *platformInterface = nullptr;
在哪里销毁的呢

2024-11-22 10:21 UTC, zccrs commented on src/kernel/dplatformtheme.cpp
> +    d->theme = new DNativeSettings(window, QByteArray(), this);
还需要它干啥？

2024-11-22 10:55 UTC, zccrs commented
/+1

2024-11-25 13:42 UTC, closed without merging