feat: Register the DciIcon as a meta type
linuxdeepin/dtkgui pull request #37
Opened 2022-07-28 07:41 UTC by cccccccb

After registering the DciIcon as a meta type, it is
convenient for applications to use it on QVariant.

The << and >> operators are provided to facilitate
applications to read and write.

Log:
Influence: None
Change-Id: I0df76a9e5378a46dcb075b2368fd05eb360d074d

2022-07-28 08:01 UTC, zccrs requested changes

2022-07-28 08:01 UTC, zccrs commented on src/util/ddciicon.cpp
> +    if (icon.isNull())
可以 s << QByteArray() 一个空的数据试试

2022-07-28 08:01 UTC, zccrs commented on src/util/ddciicon.h
> +#if !defined(QT_NO_DATASTREAM)
用 ifndef

2022-07-28 08:01 UTC, zccrs commented on src/util/ddciicon.cpp
> +QDataStream &operator<<(QDataStream &s, const DDciIcon &icon)
也应该判断 QT_NO_DATASTREAM

2022-07-29 02:03 UTC, cccccccb commented on src/util/ddciicon.cpp
> +    if (icon.isNull())
已修改

2022-07-29 02:03 UTC, cccccccb commented on src/util/ddciicon.h
> +#if !defined(QT_NO_DATASTREAM)
已修改

2022-07-29 02:03 UTC, cccccccb commented on src/util/ddciicon.cpp
> +QDataStream &operator<<(QDataStream &s, const DDciIcon &icon)
已添加

2022-07-29 03:26 UTC, zccrs requested changes

2022-07-29 03:26 UTC, zccrs commented on src/util/ddciicon.cpp
> +        return s << QByteArrayLiteral("");
QByteArrayLiteral("") 跟 QByteArray() 还是不一样的

2022-07-29 06:17 UTC, zccrs approved these changes

2022-07-29 07:31 UTC, cccccccb commented
/merge

2022-07-29 07:31 UTC, merged