fix: Cast error when platform theme changed
linuxdeepin/dtkgui pull request #62
Opened 2022-09-15 06:13 UTC by 18202781743

QMetaMethod::invoke will test whether object is an instance
of the QMetaObject as Q_ASSERT(mobj->cast(object)), but invokeOnGadge will not, and their role seem to be the same, we only use DirectConnection to invoke it.
  DPlatformTheme is inherits DNativeSettings, and it's metaobject
is changed to DNativeSettings in qt5platform-plugin.

Log: 调用invoke会做assert判断，导致当qt为debug编译时，改变主题会导致程序崩溃
Influence: 当qt为debug编译时，改变主题会导致程序崩溃
Change-Id: I9133430ba6f3df4c4a806ff9fa96ba8ec8213ce4

2022-09-15 06:13 UTC, 18202781743 commented
/review @kegechen @zccrs

2022-09-16 02:14 UTC, 18202781743 commented on src/kernel/dplatformtheme.cpp
> +        p.notifySignal().invokeOnGadget(q, QGenericArgument(value.typeName(), value.constData()));
功能是正常的,看两个函数的代码逻辑 ,是一样的,只是之前多个了异步的支持.

2022-09-16 02:22 UTC, zccrs requested changes

2022-09-16 02:22 UTC, zccrs commented on src/kernel/dplatformtheme.cpp
> +        p.notifySignal().invokeOnGadget(q, QGenericArgument(value.typeName(), value.constData()));
在这里加个注释，说明以下为什么用 invokeOnGadget 而不是 invoke

2022-09-16 02:56 UTC, 18202781743 commented on src/kernel/dplatformtheme.cpp
> +        p.notifySignal().invokeOnGadget(q, QGenericArgument(value.typeName(), value.constData()));
Done

2022-09-16 03:37 UTC, kegechen approved these changes

2022-09-16 03:38 UTC, 18202781743 commented
/merge

2022-09-16 03:50 UTC, Decodetalkers commented
/check build

2022-09-16 05:30 UTC, zccrs approved these changes

2022-09-16 06:28 UTC, kegechen approved these changes

2022-09-16 06:28 UTC, merged