feat: add DIcon
linuxdeepin/dtkgui pull request #72
Opened 2022-11-04 02:24 UTC by kegechen

get pixmap of specified devicePixelRatio
Fix https://pms.uniontech.com/bug-view-162771.html

Log: none
Change-Id: I38b16c8402be74d1ef216faf7c77fa096282dadc

2022-11-15 02:50 UTC, zccrs requested changes

2022-11-15 02:50 UTC, zccrs commented on src/util/dicon.cpp
> +    if (devicePixelRatio > 1.0) {
这个 if 里做的事情有啥意义呀？后面也没有用到。

2022-11-15 02:50 UTC, zccrs commented on src/util/dicon.cpp
> +    auto pixmapDevicePixelRatio = [](qreal displayDevicePixelRatio,
这个函数里的代码缩进有问题

2022-11-15 02:50 UTC, zccrs commented on tests/main.cpp
> +    qputenv("QT_SCALE_FACTOR","1.25");
main.cpp 中的代码会影响到所有的单元测试，不应该只服务于某一个测试用例。不设置这两个环境变量对 ut_dicon 有什么影响吗

2022-11-15 02:58 UTC, kegechen commented on src/util/dicon.cpp
> +    if (devicePixelRatio > 1.0) {
done

2022-11-15 02:59 UTC, kegechen commented on tests/main.cpp
> +    qputenv("QT_SCALE_FACTOR","1.25");
为了设置固定缩放，其他ut没有涉及到缩放的。 ut_dicon里面有根据不同缩放获取不同大小的pixmap

2022-11-15 05:20 UTC, zccrs commented on tests/main.cpp
> +    qputenv("QT_SCALE_FACTOR","1.25");
那这里要加个注释

2022-11-17 05:53 UTC, zccrs approved these changes

2022-11-17 05:54 UTC, merged