feat: add setAutoSaveApplciationTheme function
linuxdeepin/dtkgui pull request #73
Opened 2022-11-15 02:30 UTC by kegechen

保存主题功能让非 widget 应用也能用上

Log: 
Change-Id: I9e6673c0e78c25dfc7445623a93189f89cf2c076

2022-11-15 02:51 UTC, zccrs requested changes

2022-11-15 02:51 UTC, zccrs commented on src/kernel/dguiapplicationhelper.cpp
> +#include <QGSettings/QGSettings>
不要再用gsettings了，应该用 dconfig 保存

2022-11-15 05:42 UTC, kegechen commented on src/kernel/dguiapplicationhelper.cpp
> +#include <QGSettings/QGSettings>
是应该如此，不然需要引入gsettings的依赖。 不过还需等待 getappid的接口。
这个提交暂时放着吧

2023-03-22 09:35 UTC, kegechen commented
https://github.com/linuxdeepin/dtkwidget/pull/384

2023-03-23 01:28 UTC, zccrs requested changes

2023-03-23 01:28 UTC, zccrs commented on include/kernel/dguiapplicationhelper.h
> +    static void setAutoSaveApplicationTheme();
放到 Attribute 里

2023-03-23 01:28 UTC, zccrs commented on misc/org.deepin.dtk.helper.json
> +          "name": "The application palette type",
直接用“theme type”更合适些

2023-03-23 01:28 UTC, zccrs commented on misc/org.deepin.dtk.helper.json
> +      "restoredGSettings": {
加个这样的配置蛮奇怪的，可以直接忽略gsettings中的设置。

2023-03-23 01:28 UTC, zccrs commented on src/kernel/dguiapplicationhelper.cpp
> +    connect(instance(), &DGuiApplicationHelper::paletteTypeChanged, config, [appPaletteType, config](ColorType paletteType){
不要随时存储，只在 DGuiApplicationHeloper 销毁前存储一次即可。且在存储前断开与 &DConfig::valueChanged 的链接。

2023-03-23 01:28 UTC, zccrs commented on src/kernel/dguiapplicationhelper.cpp
> +        switch (config->value(appPaletteType, UnknownType).toInt()) {
这是不是不需要 switch 了，直接强制转为 PaletteType，如果大于某个值，则强制设置为 UnknownType

2023-03-23 01:28 UTC, zccrs commented on src/kernel/dguiapplicationhelper.cpp
> +    const QByteArray &appId = "org.deepin.dtk.helper";
为什么用这样的一个appId？

2023-03-23 01:30 UTC, zccrs requested changes
参见 https://github.com/linuxdeepin/dtkgui/pull/139 这个提交，可以跟它用同一个 json 文件

2023-03-23 05:10 UTC, kegechen commented
> 参见 #139 这个提交，可以跟它用同一个 json 文件

那等他这个合并了再加上相关key吧

2023-03-31 01:15 UTC, 18202781743 commented on misc/org.deepin.dtk.ui.preference.json
> +            "name[zh_CN]": "应用主题的颜色，可以设置为跟随系统(0)、浅色(1)、 深色(2)，默认为跟随系统",
这个内容是description[zh_CN]

2023-03-31 01:15 UTC, 18202781743 commented on src/kernel/dguiapplicationhelper.cpp
> +    appThemeConfig = new DConfig(appId, QString(), DGuiApplicationHelper::instance());
这个不是appId,名字可以改下，或叫metaId

2023-03-31 01:15 UTC, 18202781743 commented on src/kernel/dguiapplicationhelper.cpp
> +        appThemeConfig->setValue(appThemeType, paletteType);
如果这里监听了aboutToQuit的话，是不是可以不用将DConfig的管理给DGuiApplicationHelper::instance了，
这样的话，也不用手动disconnect了，直接在这里delete，
另外它是个static的变量，也不需要给parent了吧，

2023-03-31 01:19 UTC, 18202781743 commented on src/kernel/dguiapplicationhelper.cpp
> +        appThemeConfig->setValue(appThemeType, paletteType);
还是需要手动disconnect,不然在filebackend的话，这里是直接出发了valueChange信号了的，

2023-03-31 01:27 UTC, kegechen commented on src/kernel/dguiapplicationhelper.cpp
> +static void saveApplicationTheme(bool on = true)
想留一个开关来着，想着也没有人会一会打开一会关闭。还是去掉吧

2023-03-31 02:24 UTC, zccrs requested changes

2023-03-31 02:24 UTC, zccrs commented on debian/libdtkgui5.install
> +usr/share/dsg/*
这是之前的提交漏掉了？分开一个commit单独修复。

2023-03-31 02:24 UTC, zccrs commented on src/CMakeLists.txt
> +dconfig_meta_files(COMMONID org.deepin.dtk FILES ${PROJECT_SOURCE_DIR}/misc/org.deepin.dtk.ui.preference.json)
同上

2023-03-31 02:24 UTC, zccrs commented on src/kernel/dguiapplicationhelper.cpp
> +    DCORE_USE_NAMESPACE
重复了

2023-03-31 02:24 UTC, zccrs commented on src/kernel/dguiapplicationhelper.cpp
> +    if (appThemeConfig)
可以用 Q_GLOBAL_STATIC 定义，在这里判断，QGlobalStatic::exists()，它是线程安全的，不用自己实现这个逻辑。

2023-03-31 02:24 UTC, zccrs commented on src/kernel/dguiapplicationhelper.cpp
> +        if (q->testAttribute(DGuiApplicationHelper::SaveApplicationTheme))
如果没有设置过，默认有 SaveApplicationTheme 标志吗？

2023-04-03 01:35 UTC, kegechen commented on src/CMakeLists.txt
> +dconfig_meta_files(COMMONID org.deepin.dtk FILES ${PROJECT_SOURCE_DIR}/misc/org.deepin.dtk.ui.preference.json)
这个不一样。这个是上一个提交把这个install的逻辑放在最顶层的 `CMakeLists` 中，这里换到 `src/CMakeLists`

2023-04-03 01:35 UTC, kegechen commented on src/kernel/dguiapplicationhelper.cpp
> +        if (q->testAttribute(DGuiApplicationHelper::SaveApplicationTheme))
默认没有。只有set之后才有

2023-04-03 02:03 UTC, kegechen commented
> 参见 #139 这个提交，可以跟它用同一个 json 文件

https://github.com/linuxdeepin/dtkgui/pull/141

2023-04-03 02:04 UTC, kegechen commented on debian/libdtkgui5.install
> +usr/share/dsg/*
https://github.com/linuxdeepin/dtkgui/pull/141

2023-04-03 02:07 UTC, zccrs requested changes

2023-04-03 02:07 UTC, zccrs commented on debian/libdtkgui5.install
> +usr/share/dsg/*
这里怎么没有删掉？

2023-04-03 02:07 UTC, zccrs commented on src/CMakeLists.txt
> +dconfig_meta_files(COMMONID org.deepin.dtk FILES ${PROJECT_SOURCE_DIR}/misc/org.deepin.dtk.ui.preference.json)
我看在另一个提交里改了，这里应该删掉。

2023-04-03 02:07 UTC, zccrs commented on src/kernel/dguiapplicationhelper.cpp
> +        if (q->testAttribute(DGuiApplicationHelper::SaveApplicationTheme))
可以改成默认有，这样的话换一下 Attribute 的名字， DontSaveApplicationTheme

2023-04-10 08:53 UTC, kegechen commented on src/kernel/dguiapplicationhelper.cpp
> +        if (q->testAttribute(DGuiApplicationHelper::SaveApplicationTheme))
改成默认的话，dtkwidget中的 gsetttings 的部分可以标记废弃并且实现都去掉了。不然重复记录了

2023-04-11 01:58 UTC, zccrs requested changes

2023-04-11 01:58 UTC, zccrs commented on misc/org.deepin.dtk.ui.preference.json
> +        "appThemeType": {
直接叫  thmeType 就行，不用强调 “app”，不然dtk里的大部分配置项都是 "appXXXX" 这种形式了

2023-04-11 01:58 UTC, zccrs commented on src/kernel/dguiapplicationhelper.cpp
> +static void saveApplicationTheme()
叫 "save" 与代码实现的行为不太匹配，可以想一个更贴合的名字

2023-04-11 01:58 UTC, zccrs commented on src/kernel/dguiapplicationhelper.cpp
> +            return ;
多了个空格

2023-04-13 01:38 UTC, zccrs requested changes

2023-04-13 01:38 UTC, zccrs commented on src/kernel/dguiapplicationhelper.cpp
> +                applyThemeType();
如果是这样，在 applyThemeType 里就不应该再判断 “if (_d_dconfig.exists())” 了吧？

2023-04-13 01:41 UTC, kegechen commented on src/kernel/dguiapplicationhelper.cpp
> +                applyThemeType();
是的。

2023-04-13 07:49 UTC, zccrs approved these changes

2023-04-14 00:47 UTC, merged