feat: construct DDciIconPalette from QPalette
linuxdeepin/dtkgui pull request #79
Opened 2022-11-25 08:18 UTC by kegechen

add a way to construct DDciIconPalette from QPalette

Log: none
Influence: none
Change-Id: I4e9b9f8bf3a653c066bf92c7ba1a3ef72526e2ac

2022-11-28 01:30 UTC, 18202781743 commented
+1

2022-11-29 02:44 UTC, zccrs requested changes

2022-11-29 02:44 UTC, zccrs commented on src/util/ddciiconpalette.cpp
> -
这个空行不应该被删除

2022-11-29 02:44 UTC, zccrs commented on src/util/ddciiconpalette.cpp
> +    :DDciIconPalette(pa.foreground().color(), pa.background().color(), pa.highlight().color(), pa.highlightedText().color())
":" 后面加空格

2022-11-29 02:44 UTC, zccrs commented on include/util/ddciiconpalette.h
> +    DDciIconPalette(const QPalette &pa);
不建议加个构建函数，可以加一个
`static DDciIconPalette fromQPalette(const QPalette &pa)`
这样更合适些。

2022-11-29 03:36 UTC, zccrs requested changes

2022-11-29 03:36 UTC, zccrs commented on include/util/ddciiconpalette.h
> +class QPalette;
加上 QT_BEGIN_NAMESPACE 和 QT_END_NAMESPACE

2022-11-29 03:42 UTC, zccrs approved these changes

2022-11-29 03:42 UTC, merged