chore: 适配 XEventMonitor 服务改名
linuxdeepin/dtkgui pull request #80
Opened 2022-11-29 10:01 UTC by kegechen

修改XEventMonitor服务名为org.deepin.api.XEventMonitor1。

Log: 修改XEventMonitor服务名。
Influence: 无。

2022-11-29 10:16 UTC, 18202781743 commented on src/dbus/xeventmonitor_interface.h
> +void registerAreaListMetaType();
这个函数在哪里调用的？

2022-11-29 10:18 UTC, 18202781743 commented on src/kernel/dregionmonitor.cpp
> +    QString path("/com/deepin/api/XEventMonitor");
这种兼容性的，看要不要放到一个统一的位置，直接append("1")，感觉不太好，
之后要是找这个服务，还不一定在代码里搜的到，

2022-11-30 01:35 UTC, kegechen commented on src/dbus/xeventmonitor_interface.h
> +void registerAreaListMetaType();
有道理，只是实现了，原来的版本实现都没有

2022-12-02 00:46 UTC, 18202781743 commented
+1

2022-12-02 01:35 UTC, zccrs requested changes

2022-12-02 01:35 UTC, zccrs commented on src/dbus/dbus.cmake
> -qt5_add_dbus_interface(
怎么不继续自动生成了？

2022-12-02 01:35 UTC, zccrs commented on src/kernel/dregionmonitor.cpp
> -    , eventInter(new XEventMonitor("com.deepin.api.XEventMonitor", "/com/deepin/api/XEventMonitor", QDBusConnection::sessionBus()))
当 org.deepin.api.XEventMonitor 没有的时候要fallback到com.deepin.api.XEventMonitor

2022-12-02 01:39 UTC, kegechen commented on src/dbus/dbus.cmake
> -qt5_add_dbus_interface(
自动生成需要在编译时判断 接口 是不是新的 xeventmonitor1 , 或者冗余生成两套，再根据具体去选择，用哪一个

2022-12-02 01:51 UTC, kegechen commented on src/kernel/dregionmonitor.cpp
> -    , eventInter(new XEventMonitor("com.deepin.api.XEventMonitor", "/com/deepin/api/XEventMonitor", QDBusConnection::sessionBus()))
return isXEventMonitor1Registered() ? QLatin1String("/org/deepin/api/XEventMonitor1") : QLatin1String("/com/deepin/api/XEventMonitor");

是有fallback的

2022-12-02 01:57 UTC, zccrs requested changes

2022-12-02 01:57 UTC, zccrs commented on src/dbus/xeventmonitor_interface.cpp
> +    return QDBusConnection::sessionBus().interface()->isServiceRegistered(QLatin1String("org.deepin.api.XEventMonitor1"));
这个判断结果应该静态缓存下来，不用每次都判断，下面有三个函数中都使用了它，从当前的实现方式看，这三个函数是分别判断的，有可能会出现结果不一致的情况，这样会导致 interfaceName 是 org.xxxx，但是 serviceName 却是 com.xxxx，要从根源上杜绝这种可能性，让它们绝对一致。

2022-12-02 05:39 UTC, zccrs approved these changes

2022-12-02 05:52 UTC, merged