fix: no return value on some case
linuxdeepin/dtkgui pull request #88
Opened 2022-12-13 12:32 UTC by kegechen

no return value after asyncCall

Log: undefined behavior
Influence: none
Change-Id: I15a6aec8a8ab57e446f25fbf91c979acde667903

2022-12-14 00:25 UTC, 18202781743 commented on src/kernel/dguiapplicationhelper.cpp
> +            if (file.isDir() && file.fileName().contains(appName, Qt::CaseInsensitive)) {
获取的是Subdirectories，file.isDir()为true?

2022-12-14 00:25 UTC, 18202781743 commented on src/kernel/dguiapplicationhelper.cpp
> +            if (file.isDir())
这个是不是可以去掉？

2022-12-14 00:26 UTC, 18202781743 commented on src/kernel/dguiapplicationhelper.cpp
> +
可以提前return吧

2022-12-14 00:27 UTC, 18202781743 commented on src/kernel/dguiapplicationhelper.cpp
> +static bool loadManualFromLocalFile()
函数功能是判断能否加载，而不是加载

2022-12-14 00:31 UTC, 18202781743 submitted a review, later dismissed

2022-12-14 02:53 UTC, 18202781743 approved these changes

2022-12-16 08:12 UTC, zccrs requested changes

2022-12-16 08:12 UTC, zccrs commented on src/kernel/dguiapplicationhelper.cpp
> +        if (QFile::exists(QStringList {path, "dman"}.join(QDir::separator()))) {
怎么不直接用 QStandardPaths::findExecutable?

2022-12-19 05:27 UTC, kegechen commented on src/kernel/dguiapplicationhelper.cpp
> +        if (QFile::exists(QStringList {path, "dman"}.join(QDir::separator()))) {
https://github.com/linuxdeepin/dtkgui/pull/90

2022-12-19 05:27 UTC, kegechen commented
https://github.com/linuxdeepin/dtkgui/pull/90

2022-12-19 05:27 UTC, closed without merging