feat: Add SizeMode support
linuxdeepin/dtkgui pull request #95
Opened 2022-12-26 09:05 UTC by 18202781743

enable SizeMode support by default.
  user can set environment `D_DTK_DISABLE_TIGHTMODE` to disable
SizeMode support.
  application can disable SizeMode by `setEnabledSizeMode`.

Log: 支持紧凑模式切换
Task: https://pms.uniontech.com/task-view-227385.html
Influence: none
Change-Id: I2eefe254f9bbf380d9ab133c4eb0caa979ed1356

2022-12-27 01:23 UTC, 18202781743 commented
/review @kegechen

2022-12-27 06:48 UTC, xzl01 commented
文档！！！

2022-12-28 07:22 UTC, xzl01 commented on docs/src/dguiapplicationhelper.zh_CN.dox
> +
空行删掉

2022-12-28 07:22 UTC, xzl01 commented on docs/src/dguiapplicationhelper.zh_CN.dox
空行删掉

2022-12-28 07:26 UTC, kegechen submitted a review, later dismissed

2022-12-29 02:28 UTC, zccrs requested changes

2022-12-29 02:28 UTC, zccrs commented on include/kernel/dguiapplicationhelper.h
> +        TightMode
用 compact 是不是更合适些？

2022-12-29 02:28 UTC, zccrs commented on include/kernel/dguiapplicationhelper.h
> +    static bool isTightMode();
可以变成一个 inline 的

2022-12-29 02:28 UTC, zccrs commented on src/kernel/dguiapplicationhelper.cpp
> +    qDebug() << "sizeModeChanged(), old SizeMode:" << sizeMode << "now sizeMode:" << mode;
不要随意加debug，如果是正式的log，用 qCDebug 添加，而且输出内容要更正式一些，比如这里的 mode 就不能只输出一个 int 值，这样看log时没有意义，还得配合代码才知道这个log的意思。每一条log都要能做到自解释，也就是即便不熟悉和参考代码，也能看出这条log的所有信息。

2022-12-29 02:28 UTC, zccrs commented on src/kernel/dguiapplicationhelper.cpp
> +void DGuiApplicationHelper::setEnabledSizeMode(bool enabled)
这个函数有啥意义呢？感觉用途不大呀，enabled和非enabled的区别，与直接提供一个 setSizeMode 有区别吗？而且还不容易理解。

2022-12-29 06:14 UTC, 18202781743 commented on src/kernel/dguiapplicationhelper.cpp
> +void DGuiApplicationHelper::setEnabledSizeMode(bool enabled)
这个功能可能需要应用适配，如果不准备适配可以禁用这个功能，
sizeMode是系统级的控制，一般在控制中心控制所有应用，如果提供setSizeMode，与控制中心那里的setSizeMode意义有冲突，理解是控制所有应用，

2022-12-29 07:45 UTC, zccrs commented on src/kernel/dguiapplicationhelper.cpp
> +void DGuiApplicationHelper::setEnabledSizeMode(bool enabled)
这类似于 QStyleHints，默认肯定从系统统一设置里读，但是用户可以设置，这时候会以用户设置的值为准，但是用户设置只对当前应用有效，另外还可以提供一个resetXXX函数，用户设置被reset后则恢复到系统设置。这个设置函数只需要在 DGuiApplicationHelper中提供即可，DPlatformTheme 则不提供。

2022-12-30 04:21 UTC, 18202781743 commented
/check

2022-12-30 06:02 UTC, zccrs requested changes

2022-12-30 06:02 UTC, zccrs commented on src/kernel/dguiapplicationhelper.cpp
> +    return d->explicitSizeMode == DGuiApplicationHelper::InvalidMode ? d->systemSizeMode
explicitSizeMode 的优先级不应该高于 D_DTK_SIZEMODE 吗

2022-12-30 06:02 UTC, zccrs commented on src/kernel/dguiapplicationhelper.cpp
> +}
是不是要updateSizeMode？并且有可能触发sizeModeChanged信号

2022-12-30 06:02 UTC, zccrs commented on src/kernel/dguiapplicationhelper.cpp
> +    setSizeMode(DGuiApplicationHelper::InvalidMode);
其实不用专门搞一个 InvalidMode 来实现resize，用一个 int8 保存 explicitSizeMode 的值，再用一个bool记录是否是一个有效值就够了。

2022-12-30 07:13 UTC, 18202781743 commented on src/kernel/dguiapplicationhelper.cpp
> +    return d->explicitSizeMode == DGuiApplicationHelper::InvalidMode ? d->systemSizeMode
是的，这里有问题，

2022-12-30 07:23 UTC, 18202781743 commented on src/kernel/dguiapplicationhelper.cpp
> +}
之前的设想是，只会在所有控件初始化之前调用这个方法，另外用它作为是否开启了SizeMode的支持，
现在提供了setSizeMode和resetSizeMode，确实需要触发sizeModeChanged信号，否则两个接口就有冲突了，

2022-12-30 07:24 UTC, 18202781743 commented on src/kernel/dguiapplicationhelper.cpp
> +}
在有的typedef的dtkwidget控件，例如DPushButton，需要安装一个过滤器去处理SizeModeChangeEvent事件，希望加个判断，只有开启了SizeMode的支持后，才去加这个过滤器
提供setSizeMode是否调用的接口，bool isExplicitSetSizeMode()来提供否开启了SizeMode的支持的功能，
还是说不用提供这种接口，直接就是开启了，安装过滤器

2022-12-30 09:52 UTC, zccrs requested changes

2022-12-30 09:52 UTC, zccrs commented on src/kernel/dguiapplicationhelper.cpp
> +    qCInfo(dgAppHelper) << "Receiving that SizeMode is set to [" << static_cast<DGuiApplicationHelper::SizeMode>(mode)
这样输出的枚举值是string吗

2022-12-30 09:52 UTC, zccrs commented on src/kernel/dguiapplicationhelper.cpp
> +    if (updateSizeMode(static_cast<DGuiApplicationHelper::SizeMode>(mode)))
不用搞这么复杂，updateSizeMode这个函数基本上不需要，这样做就行了：

````cpp
auto oldSizeMode = fetchSizeMode();
systemSizeMode = mode;
auto currentSizeMode = fetchSizeMode();
if (currentSizeMode != oldSizeMode)
    QEMIT q->sizeModeChanged(currentSizeMode);
````

2022-12-30 09:52 UTC, zccrs commented on src/kernel/dguiapplicationhelper.cpp
> +        Q_EMIT sizeModeChanged(sizeMode());
这里直接用 mode 就行了

2022-12-30 09:52 UTC, zccrs commented on src/kernel/dguiapplicationhelper.cpp
> +    if (sizeMode() != old)
这里的sizeMode的调用保存一下，避免多次计算。

2022-12-30 09:52 UTC, zccrs commented on src/kernel/dguiapplicationhelper.cpp
> +}
其实即便这样做了也可能满足不了你想要的效果。如果要提供 isExplicitSetSizeMode() 这样的判断，那是不是还要提供一个 isExplicitSetSizeModeChanged 的信号，还要为DPushButton处理这个信号？如果无论如何都要处理信号，那为什么不干脆为DPushButton处理sizeModeChanged的信号呢？

2022-12-30 10:11 UTC, 18202781743 commented on src/kernel/dguiapplicationhelper.cpp
> +    qCInfo(dgAppHelper) << "Receiving that SizeMode is set to [" << static_cast<DGuiApplicationHelper::SizeMode>(mode)
是的，

2022-12-30 10:15 UTC, 18202781743 commented on src/kernel/dguiapplicationhelper.cpp
> +    if (updateSizeMode(static_cast<DGuiApplicationHelper::SizeMode>(mode)))
初始化也需要调用updatesizemode，保留这个函数免得重复，

2022-12-30 10:19 UTC, 18202781743 commented on src/kernel/dguiapplicationhelper.cpp
> +}
主要是dpushbutton.我们没重写，只是个typedef，所以才要安装个事件过滤器，
确实需要再加个信号，如果动态enabled的话，所以之前设想用户初始化前调用一次setSizeMode，不做信号处理，也不准备要reset的接口，

2022-12-30 10:21 UTC, 18202781743 commented on src/kernel/dguiapplicationhelper.cpp
> +    if (updateSizeMode(static_cast<DGuiApplicationHelper::SizeMode>(mode)))
还有初始化的时候也有updatesizemode的逻辑，

2023-01-03 01:55 UTC, 18202781743 commented on src/kernel/dguiapplicationhelper.cpp
> +    if (updateSizeMode(static_cast<DGuiApplicationHelper::SizeMode>(mode)))
确实可以去掉了，

2023-01-03 02:43 UTC, zccrs commented on src/kernel/dguiapplicationhelper.cpp
> +}
需要为这一类typedef的类做些什么处理呢？

2023-01-03 02:56 UTC, 18202781743 commented on src/kernel/dguiapplicationhelper.cpp
> +}
SizeMode会实时切换，在接受到事件后，有些控件对sizeHint有缓存，需要将缓存清除掉，像pushbutton，
bool DPushButtonSizeModeEventFilter::eventFilter(QObject *watched, QEvent *event)
{
    if (event->type() == DSizeModeChangeEvent::type() && watched == parent()) {
        if (auto widget = qobject_cast<QAbstractButton *>(parent())) {
            static_cast<QAbstractButtonPrivate*>(widget->d_ptr.data())->sizeHint = QSize();
        }
    }
    return QObject::eventFilter(watched, event);
}
有这样的修改，

2023-01-03 06:23 UTC, zccrs commented on src/kernel/dguiapplicationhelper.cpp
> +}
如果是这样的话，都不用专门搞一个 SizeModeChange 的事件，sizeMode这个东西会影响的是当前的DStyle，如果这个QWidget的style用的是DStyle，在sizeMode变化时给这个QWidget发一个 QEvent::StyleChange 的事件就行了，也不用管是typedef还是dtkwidget里自己实现的类，也不用专门处理 static_cast<QAbstractButtonPrivate>(widget->d_ptr.data())->sizeHint = QSize(); 这种东西，因为处理不完，根本不知道其它类还需不需要做什么特殊处理。

2023-01-03 09:53 UTC, 18202781743 commented on src/kernel/dguiapplicationhelper.cpp
> +}
看了StyleChange事件，确实应该能够满足这边的需求，之前不知道有这个，自己绕路写的跟这个功能类似，
之后修改widget的提交，gui的这笔可以不用带enableSizeMode这种接口，

2023-01-04 02:05 UTC, zccrs requested changes

2023-01-04 02:05 UTC, zccrs commented on src/private/dguiapplicationhelper_p.h
> +    Q_SLOT void _q_sizeModeChanged(int mode);
不应该加 Q_SLOT，没有意义，这个宏只能用在QObject对象里。

2023-01-04 02:05 UTC, zccrs commented on src/private/dguiapplicationhelper_p.h
> +    DGuiApplicationHelper::SizeMode explicitSizeMode;
综合一下吧，用 -1 表示无效的 sizeMode，不搞一个变量单独存储了。
在cpp里定义一个 `static DGuiApplicationHelper::SizeMode invalidSizeMode = static_cast<...>(-1)`

2023-01-04 02:08 UTC, zccrs approved these changes

2023-01-04 02:08 UTC, zccrs commented on src/kernel/dguiapplicationhelper.cpp
> +    qCInfo(dgAppHelper) << "Receiving that SizeMode is set to [" << static_cast<DGuiApplicationHelper::SizeMode>(mode)
这个log里应该标识出是 system size mode

2023-01-04 02:09 UTC, zccrs requested changes

2023-01-04 02:09 UTC, zccrs commented on src/kernel/dguiapplicationhelper.cpp
> +                *isSystemSizeMode = false;
不用重复搞，可以提到最前面，统一先设置为false

2023-01-06 05:00 UTC, merged